name:    inventory-repair-app
version: "0.0.0"
#build-type: "Custom"
build-type: "Simple"
dependencies:

# Due to a bug in GHC 8.0.1, we block its usage
# See: https://ghc.haskell.org/trac/ghc/ticket/12130
- base >=4.8.2.0 && <4.9 || >=4.9.1.0 && <5
- yesod >=1.6 && <1.7
- yesod-core >=1.6 && <1.7
- yesod-auth >=1.6 && <1.7
- yesod-static >=1.6 && <1.7
#- yesod-form >=1.6 && <1.7
- yesod-auth-oauth2 >=0.5 && <0.7
- morpheus-graphql    >= 0.15.0
- hoauth2 >=1.3.0 && <1.20
- cryptonite >= 0.25
- random  >= 1.1
- raw-strings-qq
- uri-bytestring-aeson
- classy-prelude >=1.4 && <1.6
- classy-prelude-conduit >=1.4 && <1.6
- classy-prelude-yesod >=1.4 && <1.6
- bytestring >=0.9 && <0.11
- wai-conduit
- conduit-extra
- mtl
- text >=0.11 && <2.0
- persistent # >=2.8 && <2.9
- esqueleto
- persistent-postgresql # >=2.8 && <2.9
- persistent-template >=2.5 && <3.0
- template-haskell
- shakespeare >=2.0 && <2.1
- hjsmin >=0.1 && <0.3
- monad-control >=0.3 && <1.1
- wai-extra >=3.0 && <3.5
- yaml # >=0.8 && <0.9
- http-client-tls >=0.3 && <0.4
- http-conduit >=2.3 && <2.4
- directory >=1.1 && <1.4
- warp >=3.0 && <3.4
- data-default
- aeson >=1.3.0.0 && <2.0
- conduit >=1.0 && <2.0
- monad-logger >=0.3 && <0.4
- fast-logger >=3.0 && <=3.5.0
- wai-logger >=2.2 && <2.4
- file-embed
- safe
- unordered-containers
- containers
- vector
- time
- case-insensitive
- wai
- foreign-store

# The library contains all of our application code. The executable
# defined below is just a thin wrapper.
library:
  source-dirs: src
  when:
  - condition: (flag(dev)) || (flag(library-only))
    then:
      ghc-options:
      - -Wall
      - -fwarn-tabs
      - -O0
      cpp-options: -DDEVELOPMENT
    else:
      ghc-options:
      - -Wall
      - -fwarn-tabs
      - -O0
#      - -O2

# Runnable executable for our application
executables:
  inventory-repair-app:
    main: main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - inventory-repair-app
    when:
    - condition: flag(library-only)
      buildable: false

# Test suite
tests:
  inventory-repair-app-test:
    main: Spec.hs
    source-dirs: test
    ghc-options: -Wall
    dependencies:
    - inventory-repair-app
    - hspec >=2.0.0
    - yesod-test

# Define flags used by "yesod devel" to make compilation faster
flags:
  library-only:
    description: Build for use with "yesod devel"
    manual: false
    default: false
  dev:
    description: Turn on development settings, like auto-reload templates.
    manual: false
    default: false
